<?php

/**
 * Argentina Places
 * @author   Marketing Rapel
 * @version  1.1.26
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['AR'] = array(
	'B' => array(
        'Ciudad Autónoma de Buenos Aires',
		'Adolfo Alsina',
		'Adolfo Gonzales Chaves',
		'Alberti',
'Adrogué (Almirante Brown)',
'Burzaco (Almirante Brown)',
'Claypole (Almirante Brown)',
'Don Orione (Almirante Brown)',
'Glew (Almirante Brown)',
'José Mármol (Almirante Brown)',
'Longchamps (Almirante Brown)',
'Malvinas Argentinas (Almirante Brown)',
'Ministro Rivadavia (Almirante Brown)',
'Rafael Calzada (Almirante Brown)',
'San Francisco Solano (Almirante Brown)',
'San José (Almirante Brown)',
		'Arrecifes',
'Avellaneda (Avellaneda)',
'Dock Sud (Avellaneda)',
'Gerli (Avellaneda)',
'Piñeyro (Avellaneda)',
'Sarandí (Avellaneda)',
'Villa Domínico (Avellaneda)',
'Wilde (Avellaneda)',
		'Ayacucho',
		'Azul',
		'Bahía Blanca',
		'Balcarce',
		'Baradero',
		'Benito Juárez',
'Berazategui (Berazategui)',
'El Pato (Berazategui)',
'Gutiérrez (Berazategui)',
'Hudson (Berazategui)',
'Pereyra (Berazategui)',
'Plátanos (Berazategui)',
'Ranelagh (Berazategui)',
'Sourigues (Berazategui)',
'Villa España (Berazategui)',
		'Berisso',
		'Bolívar',
		'Bragado',
		'Brandsen',
		'Campana',
		'Cañuelas',
		'Capitán Sarmiento Carlos',
		'Carlos Casares',
		'Carlos Tejedor',
		'Carmen de Areco',
		'Castelli',
		'Chacabuco',
		'Chascomús',
		'Chivilcoy',
		'Colón',
		'Coronel de Marina Leonardo Rosales',
		'Coronel Dorrego',
		'Coronel Pringles',
		'Coronel Suárez',
		'Daireaux',
		'Dolores',
		'Ensenada',
'Belén de Escobar (Escobar)',
'El Cazador (Escobar)',
'Garín (Escobar)',
'Ingeniero Maschwitz (Escobar)',
'Loma Verde (Escobar)',
'Maquinista Savio (Escobar)',
'Matheu (Escobar)',
'Canning (Esteban Echeverría)',
'El Jagüel (Esteban Echeverría)',
'Luis Guillón (Esteban Echeverría)',
'Monte Grande (Esteban Echeverría)',
'Nueve de Abril (Esteban Echeverría)',
		'Exaltación de la Cruz',
		'Ezeiza',
'Bosques (Florencio Varela)',
'Gobernador Costa (Florencio Varela)',
'Ingeniero Allan (Florencio Varela)',
'La Capilla (Florencio Varela)',
'San Juan Bautista (Florencio Varela)',
'Santa Rosa (Florencio Varela)',
'Villa Brown (Florencio Varela)',
'Villa San Luis (Florencio Varela)',
'Villa Vatteone (Florencio Varela)',
'Zeballos (Florencio Varela)',
		'Florentino Ameghino',
		'General Alvarado',
		'General Alvear',
		'General Arenales',
		'General Belgrano',
		'General Guido',
		'General Juan Madariaga',
		'General La Madrid',
'General Hornos (General Las Heras)',
'General Las Heras (General Las Heras)',
'Villars (General Las Heras)',
		'General Lavalle',
		'General Paz',
		'General Pinto',
		'General Pueyrredón',
		'General Rodríguez',
		'General San Martín',
		'General Viamonte',
		'General Villegas',
		'Guaminí',
		'Hipólito Yrigoyen',
'Hurlingham (Hurlingham)',
'Villa Tesei (Hurlingham)',
'William C. Morris (Hurlingham)',
'Ituzaingó (Ituzaingó)',
'Villa Udaondo (Ituzaingó)',
		'José C. Paz',
		'Junín',
		'La Costa',
'Aldo Bonzi (La Matanza)',
'Ciudad Evita (La Matanza)',
'González Catán (La Matanza)',
'Gregorio de Laferrere (La Matanza)',
'Isidro Casanova (La Matanza)',
'La Tablada (La Matanza)',
'Lomas del Mirador (La Matanza)',
'Rafael Castillo (La Matanza)',
'Ramos Mejía (La Matanza)',
'San Justo (La Matanza)',
'Tapiales (La Matanza)',
'Veinte de Junio (La Matanza)',
'Villa Luzuriaga (La Matanza)',
'Villa Madero (La Matanza)',
'Virrey del Pino (La Matanza)',
		'La Plata',
'Gerli (Lanús)',
'Lanús Este (Lanús)',
'Lanús Oeste (Lanús)',
'Monte Chingolo (Lanús)',
'Remedios de Escalada (Lanús)',
'Valentín Alsina (Lanús)',
		'Laprida',
		'Las Flores',
		'Leandro N. Alem',
		'Lincoln',
		'Lobería',
		'Lobos',
'Banfield (Lomas de Zamora)',
'Ingeniero Budge (Lomas de Zamora)',
'Llavallol (Lomas de Zamora)',
'Lomas de Zamora (Lomas de Zamora)',
'San José (Lomas de Zamora)',
'Temperley (Lomas de Zamora)',
'Turdera (Lomas de Zamora)',
'Villa Centenario (Lomas de Zamora)',
'Villa Fiorito (Lomas de Zamora)',
		'Luján',
		'Magdalena',
		'Maipú',
'El Triángulo (Malvinas Argentinas)',
'Grand Bourg (Malvinas Argentinas)',
'Ingeniero Adolfo Sordeaux (Malvinas Argentinas)',
'Los Polvorines (Malvinas Argentinas)',
'Malvinas Argentinas (Malvinas Argentinas)',
'Pablo Nogués (Malvinas Argentinas)',
'Tierras Altas (Malvinas Argentinas)',
'Tortuguitas (Malvinas Argentinas)',
'Villa de Mayo (Malvinas Argentinas)',
		'Mar Chiquita',
		'Marcos Paz',
		'Mercedes',
'Libertad (Merlo)',
'Mariano Acosta (Merlo)',
'Merlo (Merlo)',
'Parque San Martín (Merlo)',
'Pontevedra (Merlo)',
'San Antonio de Padua (Merlo)',
		'Monte',
		'Monte Hermoso',
'Cuartel V (Moreno)',
'Francisco Álvarez (Moreno)',
'La Reja (Moreno)',
'Mariano Moreno (Moreno)',
'Paso del Rey (Moreno)',
'Trujui (Moreno)',
'Castelar (Morón)',
'El Palomar (Morón)',
'Haedo (Morón)',
'Morón (Morón)',
'Villa Sarmiento (Morón)',
		'Navarro',
		'Necochea',
		'Nueve de Julio (9 de Julio)',
		'Olavarría',
		'Patagones',
		'Pehuajó',
		'Pellegrini',
		'Pergamino',
		'Pila',
		'Pilar',
		'Pinamar',
		'Presidente Perón',
		'Puan',
		'Punta Indio',
'Bernal (Quilmes)',
'Don Bosco (Quilmes)',
'Ezpeleta (Quilmes)',
'Quilmes (Quilmes)',
'San Francisco Solano (Quilmes)',
'Villa La Florida (Quilmes)',
		'Ramallo',
		'Rauch',
		'Rivadavia',
		'Rojas',
		'Roque Pérez',
		'Saavedra',
		'Saladillo',
		'Salliqueló',
		'Salto',
		'San Andrés de Giles',
		'San Antonio de Areco',
		'San Cayetano',
'Islas (San Fernando)',
'San Fernando (San Fernando)',
'Victoria (San Fernando)',
'Virreyes (San Fernando)',
'Acassuso (San Isidro)',
'Beccar (San Isidro)',
'Boulogne (San Isidro)',
'Martínez (San Isidro)',
'San Isidro (San Isidro)',
'Villa Adelina (San Isidro)',
'Bella Vista (San Miguel)',
'Campo de Mayo (San Miguel)',
'Muñiz (San Miguel)',
'San Miguel (San Miguel)',
'Santa María (San Miguel)',
		'San Nicolás',
		'San Pedro',
		'San Vicente',
		'Suipacha',
		'Tandil',
		'Tapalqué',
'Benavídez (Tigre)',
'Delta de Tigre (Tigre)',
'Dique Luján (Tigre)',
'Don Torcuato (Tigre)',
'El Talar (Tigre)',
'General Pacheco (Tigre)',
'Nordelta (Tigre)',
'Ricardo Rojas (Tigre)',
'Rincón de Milberg (Tigre)',
'Tigre (Tigre)',
'Troncos del Talar (Tigre)',
		'Tordillo',
		'Tornquist',
		'Trenque Lauquen',
		'Tres Arroyos',
'Caseros (Tres de Febrero)',
'Churruca (Tres de Febrero)',
'Ciudad Jardín Lomas de El Palomar (Tres de Febrero)',
'Ciudadela (Tres de Febrero)',
'El Libertador (Tres de Febrero)',
'Loma Hermosa (Tres de Febrero)',
'Martín Coronado (Tres de Febrero)',
'Once de Septiembre (Tres de Febrero)',
'Pablo Podestá (Tres de Febrero)',
'Remedios de Escalada de San Martín (Tres de Febrero)',
'Sáenz Peña (Tres de Febrero)',
'Santos Lugares (Tres de Febrero)',
'Villa Bosch (Tres de Febrero)',
'Villa Raffo (Tres de Febrero)',
		'Tres Lomas',
		'Veinticinco de Mayo (25 de Mayo)',
'Carapachay (Vicente López)',
'Florida (Vicente López)',
'Florida Oeste (Vicente López)',
'La Lucila (Vicente López)',
'Munro (Vicente López)',
'Olivos (Vicente López)',
'Vicente López (Vicente López)',
'Villa Adelina (Vicente López)',
'Villa Martelli (Vicente López)',
		'Villa Gesell',
		'Villarino',
		'Zárate'
	),
	'K' => array(
		'Ambato',
		'Ancasti',
		'Andalgalá',
		'Antofagasta de la Sierra',
		'Belén',
		'Capayán',
		'Catamarca',
		'El Alto',
		'Fray Mamerto Esquiú',
		'La Paz',
		'Paclín',
		'Pomán',
		'Santa María',
		'Santa Rosa',
		'Tinogasta',
		'Valle Viejo'
	),
	'H' => array(
		'Almirante Brown',
		'Bermejo',
		'Chacabuco',
		'Comandante Fernández',
		'Doce de Octubre (12 de Octubre)',
		'Dos de Abril (2 de Abril)',
		'Fray Justo Santa María de Oro',
		'General Belgrano',
		'General Donovan',
		'General Güemes',
		'Independencia',
		'Libertad',
		'Libertador General San Martín',
		'Maipú',
		'Mayor Luis Jorge Fontana',
		'Nueve de Julio (9 de Julio)',
		'O\'Higgins',
		'Presidencia de la Plaza',
		'Primero de Mayo (1º de Mayo)',
		'Quitilipi',
		'San Fernando',
		'San Lorenzo',
		'Sargento Cabral',
		'Tapenagá',
		'Veinticinco de Mayo (25 de Mayo)',
	),
	'U' => array(
		'Biedma',
		'Cushamen',
		'Escalante',
		'Florentino Ameghino',
		'Futaleufú',
		'Gaiman',
		'Gastre',
		'Languiñeo',
		'Mártires',
		'Paso de Indios',
		'Rawson',
		'Río Senguer',
		'Sarmiento',
		'Tehuelches',
		'Telsen'
	),
	'X' => array(
		'Calamuchita',
		'Córdoba',
		'Colón',
		'Cruz del Eje',
		'General Roca',
		'General San Martín',
		'Ischilín',
		'Juárez Celman',
		'Marcos Juárez',
		'Minas',
		'Pocho',
		'Presidente Roque Sáenz Peña',
		'Punilla',
		'Río Cuarto',
		'Río Primero',
		'Río Seco',
		'Río Segundo',
		'San Alberto',
		'San Javier',
		'San Justo',
		'Santa María',
		'Sobremonte',
		'Tercero Arriba',
		'Totoral',
		'Tulumba',
		'Unión'
	),
	'W' => array(
		'Bella Vista',
		'Berón de Astrada',
		'Corrientes',
		'Concepción',
		'Curuzú Cuatiá',
		'Empedrado',
		'Esquina',
		'General Alvear',
		'General Paz',
		'Goya',
		'Itatí',
		'Ituzaingó',
		'Lavalle',
		'Mburucuyá',
		'Mercedes',
		'Monte Caseros',
		'Paso de los Libres',
		'Saladas',
		'San Cosme',
		'San Luis del Palmar',
		'San Martín',
		'San Miguel',
		'San Roque',
		'Santo Tomé',
		'Sauce'
	),
	'E' => array(
		'Colón',
		'Concordia',
		'Diamante',
		'Federación',
		'Federal',
		'Feliciano',
		'Gualeguay',
		'Gualeguaychú',
		'Islas del Ibicuy',
		'La Paz',
		'Nogoyá',
		'Paraná',
		'San Salvador',
		'Tala',
		'Uruguay',
		'Victoria',
		'Villaguay'
	),
	'P' => array(
		'Bermejo',
		'Formosa',
		'Laishi',
		'Matacos',
		'Patiño',
		'Pilagás',
		'Pilcomayo',
		'Pirané',
		'Ramón Lista'
	),
	'Y' => array(
		'Cochinoca',
		'Doctor Manuel Belgrano',
		'El Carmen',
		'Humahuaca',
		'Ledesma',
		'Palpalá',
		'Rinconada',
		'San Antonio',
		'San Pedro',
		'Santa Bárbara',
		'Santa Catalina',
		'Susques',
		'Tilcara',
		'Tumbaya',
		'Valle Grande',
		'Yavi'
	),
	'L' => array(
		'Atreucó',
		'Caleu Caleu',
		'Capital',
		'Catriló',
		'Chalileo',
		'Chapaleufú',
		'Chical Co',
		'Conhelo',
		'Curacó',
		'Guatraché',
		'Hucal',
		'Lihuel Calel',
		'Limay Mahuida',
		'Loventué',
		'Maracó',
		'Puelén',
		'Quemú Quemú',
		'Rancul',
		'Realicó',
		'Toay',
		'Trenel',
		'Utracán'
	),
	'F' => array(
		'Arauco',
		'La Rioja',
		'Castro Barros',
		'Chamical',
		'Chilecito',
		'Coronel Felipe Varela',
		'Famatina',
		'General Ángel V. Peñaloza',
		'General Belgrano',
		'General Juan Facundo Quiroga',
		'General Lamadrid',
		'General Ocampo',
		'General San Martín',
		'Independencia',
		'Rosario Vera Peñaloza',
		'Sanagasta',
		'San Blas de los Sauces',
		'Vinchina'
	),
	'M' => array(
		'Mendoza',
		'General Alvear',
		'Godoy Cruz',
		'Guaymallén',
		'Junín',
		'La Paz',
		'Las Heras',
		'Lavalle',
		'Luján de Cuyo',
		'Maipú',
		'Malargüe',
		'Rivadavia',
		'San Carlos',
		'San Martín',
		'San Rafael',
		'Santa Rosa',
		'Tunuyán',
		'Tupungato'
	),
	'N' => array(
		'Apóstoles',
		'Cainguás',
		'Candelaria',
		'Misiones',
		'Concepción',
		'Eldorado',
		'General Manuel Belgrano',
		'Guaraní',
		'Iguazú',
		'Leandro N. Alem',
		'Libertador General San Martín',
		'Montecarlo',
		'Oberá',
		'San Ignacio',
		'San Javier',
		'San Pedro',
		'Veinticinco de Mayo (25 de Mayo)'
	),
	'Q' => array(
		'Aluminé',
		'Añelo',
		'Catán Lil',
		'Chos Malal',
		'Collón Curá',
		'Confluencia',
		'Huiliches',
		'Lácar',
		'Loncopué',
		'Los Lagos',
		'Minas',
		'Ñorquín',
		'Pehuenches',
		'Picunches',
		'Picún Leufú',
		'Zapala'
	),
	'R' => array(
		'Adolfo Alsina',
		'Avellaneda',
		'Bariloche',
		'Conesa',
		'El Cuy',
		'General Roca',
		'Ñorquincó',
		'Nueve de Julio (9 de Julio)',
		'Pichi Mahuida',
		'Pilcaniyeu',
		'San Antonio',
		'Valcheta',
		'Veinticinco de Mayo (25 de Mayo)'
	),
	'A' => array(
		'Anta',
		'Cachi',
		'Cafayate',
		'Salta',
		'Cerrillos',
		'Chicoana',
		'General Güemes',
		'General José de San Martín',
		'Guachipas',
		'Iruya',
		'La Caldera',
		'La Candelaria',
		'La Poma',
		'La Viña',
		'Los Andes',
		'Metán',
		'Molinos',
		'Orán',
		'Rivadavia',
		'Rosario de la Frontera',
		'Rosario de Lerma',
		'San Carlos',
		'Santa Victoria'
	),
	'J' => array(
		'Albardón',
		'Angaco',
		'Calingasta',
		'San Juan',
		'Caucete',
		'Chimbas',
		'Iglesia',
		'Jáchal',
		'Nueve de Julio (9 de Julio)',
		'Pocito',
		'Rawson',
		'Rivadavia',
		'San Martín',
		'Santa Lucía',
		'Sarmiento',
		'Ullum',
		'Valle Fértil',
		'Veinticinco de Mayo (25 de Mayo)',
		'Zonda'
	),
	'D' => array(
		'Ayacucho',
		'Belgrano',
		'Chacabuco',
		'Coronel Pringles',
		'General Pedernera',
		'Gobernador Dupuy',
		'Junín',
		'La Capital (Juan Martín de Pueyrredón)',
		'Libertador General San Martín'
	),
	'Z' => array(
		'Corpen Aike',
		'Deseado',
		'Güer Aike',
		'Lago Argentino',
		'Lago Buenos Aires',
		'Magallanes',
		'Río Chico'
	),
	'S' => array(
		'Belgrano',
		'Caseros',
		'Castellanos',
		'Constitución',
		'Garay',
		'General López',
		'General Obligado',
		'Iriondo',
		'La Capital',
		'Las Colonias',
		'Nueve de Julio (9 de Julio)',
		'Rosario',
		'San Cristóbal',
		'San Javier',
		'San Jerónimo',
		'San Justo',
		'San Lorenzo',
		'San Martín',
		'Vera'
	),
	'G' => array(
		'Aguirre',
		'Alberdi',
		'Atamisqui',
		'Avellaneda',
		'Banda',
		'Belgrano',
		'Santiago del Estero',
		'Choya',
		'Copo',
		'Figueroa',
		'General Taboada',
		'Guasayán',
		'Jiménez',
		'Juan F. Ibarra',
		'Loreto',
		'Mitre',
		'Moreno',
		'Ojo de Agua',
		'Pellegrini',
		'Quebrachos',
		'Río Hondo',
		'Rivadavia',
		'Robles',
		'Salavina',
		'San Martín',
		'Sarmiento',
		'Silípica',
	),
	'V' => array(
		'Antártida Argentina',
		'Islas del Atlántico Sur',
		'Río Grande',
		'Ushuaia'
	),
	'T' => array(
		'Burruyacú',
		'Tucumán',
		'Chicligasta',
		'Cruz Alta',
		'Famaillá',
		'Graneros',
		'Juan Bautista Alberdi',
		'La Cocha',
		'Leales',
		'Lules',
		'Monteros',
		'Río Chico',
		'Simoca',
		'Tafí del Valle',
		'Tafí Viejo',
		'Trancas',
		'Yerba Buena'
	)
);